#ifndef MVV_PARSER_AST_FILES2_H_
# define MVV_PARSER_AST_FILES2_H_

# include "ast.h"
# include "ast-exp-int.h"
# include "ast-exp-float.h"
# include "ast-exp-string.h"
# include "ast-exp.h"
# include "ast-exp-op-bin.h"
# include "ast-if.h"
# include "ast-statements.h"
# include "ast-exp-assign.h"
# include "ast-var.h"
# include "ast-var-simple.h"
# include "ast-var-array.h"
# include "ast-var-field.h"
# include "ast-type.h"
# include "ast-decl.h"
# include "ast-decl-var.h"
# include "ast-decl-fun.h"
# include "ast-decl-vars.h"
# include "ast-decls.h"
# include "ast-args.h"
# include "ast-return.h"
# include "ast-import.h"
# include "ast-include.h"
# include "ast-exp-call.h"
# include "ast-decl-class.h"
# include "ast-exp-seq.h"
# include "ast-typefield.h"
# include "ast-exp-typename.h"
# include "ast-nil.h"
# include "ast-this.h"

#endif
